ServerName aquiletour.ca:443
SSLProxyEngine On

# wss
ProxyPass /wss wss://localhost:30002/                disablereuse=On
ProxyPassReverse /wss wss://localhost:30002/         disablereuse=On

# teacher
ProxyPass /mbergeron http://localhost:30001/mbergeron
ProxyPassReverse /mbergeron http://localhost:30001/mbergeron

# disptach
ProxyPass / http://localhost:30001/
ProxyPassReverse / http://localhost:30001/
